Add Github action workflow for build and release
mobilecoinofficial/full-service-mirror pull request #27
Opened 2022-03-04 08:28 UTC by MCrank

Soundtrack of this PR: [Night Flow](https://www.youtube.com/watch?v=K8kXcNqWN8g)

## Motivation
This PR adds full Build and Release of the Ledger Validator System by automating the code builds for the 4 binaries that make up the Ledger Validator Service.  This GitHub Action workflow will automatically bump the tags and produce both pre-releases and final releases.  Downloadable artifacts are created and saved to the Action output if it is not of one of the release types. The workflow will also create Docker Images for pushed tags and publish them to Docker Hub and these will be used to automatically deploy to our Kubernetes clusters .

## Included In this PR:
- Monitors for `push` events to the following branches and tags
  - main
  - develop
  - release/*
  - feature/*
  - v* (tags)
- Builds the 4 binaries
  - full-service
  - mc-validator-service
  - wallet-service-mirror-private
  - wallet-service-mirror-public
- Push to any of the above branches except main and develop
  - Code is built and if successful an artifact is created and uploaded to the GitHub action output. This should be the same format as if you created the build locally with the shell scripts.
    - The file is a zip with the tar.gz inside. Limited to how GitHub handles these but the tar file has the commit hash in the name if you need to know what code is inside.
    - ![image](https://user-images.githubusercontent.com/3493649/156723682-2a3a1e67-8088-40db-8686-264f266826aa.png)
- Push to `develop` branch
  -  Code is built and if successful the `tag` job is kicked off.
  - Tag job will look at the latest tag and by default bump the `patch` version and will apply the suffix `pre.x` where x is an incremental number for subsequent pushes to develop branch.
  - The push of the tag will kick off the workflow again but this time will publish a release with the tag the was bumped.
  - ![image](https://user-images.githubusercontent.com/3493649/156724716-eae74d0d-5e2a-4624-bcc5-213cc2cbf688.png)
  - Pre-release is created and posted to Repo releases with downloadable assets
  - ![image](https://user-images.githubusercontent.com/3493649/156725097-d21f1cd5-aaf2-4293-baba-0b8395493470.png)
  - Docker images are also created with the tag and uploaded to Docker Hub `mobilecoin/full-service-mirror`
- Push to `main` branch
  - The process is the same as for Develop except this time it creates a tagged version with the the `pre.x` and produces an official release with the assets
  - ![image](https://user-images.githubusercontent.com/3493649/156725747-3f68046c-1d61-497b-9c23-bce7e7cad75d.png)

> **You can supply one of the following commands in the commit message to adjust what gets bumped in the semver.**
> "#major", "#minor", "#patch". "#none"

## Future Work
- Update Helm chart to add the `mc-validator-service`
- Wire up the deploy steps so when code is pushed to develop or main that version gets auto deployed to the kubernetes clusters for testing/validation

2022-03-04 17:08 UTC, jgreat requested changes
This is great.  The cache buster option is a good idea.

I'm not sure the rust package cache will would right now.  The rust-sgx-base image moves the cargo home so it doesn't get squashed by GHA taking over the home directory, this way you can take advantage of pre-installed rust targets.

A couple of other optimizations, but they are not critical.

2022-03-04 17:16 UTC, jgreat commented on .github/workflows/ci.yml
> +          if [[ $GITHUB_REF == *"pre"* ]]; then
probably doesn't matter, but might be better to use `GITHUB_REF_NAME` and just get branch/tag value?

2022-03-04 22:54 UTC, MCrank commented on .github/workflows/ci.yml
> +      # CACHE_VERSION is 'date --iso-8601=minutes' and is used to invalidate cache if needed
:tada:

2022-03-04 22:54 UTC, MCrank commented on .github/workflows/ci.yml
> +        if: github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/v')
Good catch and much cleaner.

2022-03-04 22:55 UTC, MCrank commented on .github/workflows/ci.yml
> +          if [[ $GITHUB_REF == *"pre"* ]]; then
Changed the `if` statement and seems to work in my testing.

2022-03-04 22:56 UTC, MCrank commented on .github/workflows/ci.yml
> +            ~/.cargo/bin/
Updated with the correct paths.

2022-03-04 22:57 UTC, MCrank commented on .github/workflows/ci.yml
> +      - name: Get the Tag
Yeah I was searching around and I think I must have come across some old SO posts where maybe this wasn't implemented yet :shrug: .  Either way changed and tested.  Another good catch and cleaned up some code.  :checkered_flag:

2022-03-04 23:27 UTC, jgreat approved these changes
LGTM

2022-03-21 18:29 UTC, BrianCorbin commented
@MCrank how are we doing on this, any updates since our last conversation?

2022-03-22 17:26 UTC, jgreat approved these changes
LGTM

2022-03-28 18:14 UTC, merged